source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'XLForm' do

pod 'XLForm', :path => '../../'

#Following pods are used for custom row examples
pod 'AFNetworking', '~> 2.0', :inhibit_warnings => true
pod 'XLData', :git => 'https://github.com/xmartlabs/XLData.git', :commit => '1f9019b56242a2019c7f7e11ec4ef823c397ebcf', :inhibit_warnings => true
pod 'JVFloatLabeledTextField', '1.0.2', :inhibit_warnings => true
pod 'AXRatingView', '1.0.3', :inhibit_warnings => true
pod 'SHSPhoneComponent'


pod 'JKCategories'
pod 'Masonry'
pod 'ChameleonFramework'
pod 'CustomIOSAlertView'
pod 'Toast'
pod 'Mantle'

# 二维码扫描
pod 'LBXScan/LBXNative'
pod 'LBXScan/UI'

# 更改所有第三方框架 Target 版本
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
  end
end

end
